import { ArrowLeft, ShieldCheck, FileText } from 'lucide-react';
import './legal.css';

type LegalKind = 'privacy' | 'terms';

const serviceOperator = 'Thiep David Thiep';
const operatorAddress = 'Marwadi University, Rajkot, Gujarat 360003, India';
const contactEmail = 'imanchan000@gmail.com';
const governingLaw = 'India';

const sections: Record<LegalKind, Array<{ title: string; body: string }>> = {
  privacy: [
    { title: 'Who this policy covers', body: `This policy describes the information BizPilot handles when an account owner or team member uses the BizPilot business-management app, or when a customer uses a business’s public booking page or payment link. Service operator: ${serviceOperator}. Public mailing address: ${operatorAddress}. Privacy contact: ${contactEmail}.` },
    { title: 'Information in BizPilot', body: 'BizPilot processes account details such as name and email; business profile details such as business type, country, address, currency, and time zone; and records users choose to add. These records can include products and stock variants, services, customer names and contact details, customer notes, appointments and booking requests, invoices and line items, payment records, expenses, campaigns, booking hours, and payment-account connection status. A public booking page may collect a customer’s name, contact details, selected service, and requested time.' },
    { title: 'How information is used', body: 'The app uses this information to sign users in, associate records with a business workspace, display and update records, calculate inventory and business summaries, manage appointments and booking availability, prepare invoices and payment links, record payment status, provide reports, and protect the service. BizPilot does not need full card numbers to record a payment.' },
    { title: 'External services and information sharing', body: 'BizPilot uses Supabase for authentication and cloud database services; Vercel and Render to deliver and run the app and API; Stripe for connected-business payment processing and BizPilot subscription checkout; and Razorpay where enabled for payment links. When address autocomplete is used, the typed place or address query and selected country are sent to Geoapify. The app may request currency exchange rates from Frankfurter. These providers process information under their own terms and privacy policies. BizPilot does not sell business workspace records.' },
    { title: 'AI assistant', body: 'If a user chooses to use the AI assistant, BizPilot sends the question, recent chat messages, and an aggregate business snapshot to OpenAI to generate a reply. The snapshot can include counts and totals for customers, appointments, unpaid invoices, payments, and expenses, plus the business currency. The app’s snapshot excludes customer names, customer contact details, private notes, and individual customer records. Do not put personal, confidential, or sensitive information in an AI prompt.' },
    { title: 'CSV files and exports', body: 'Customer CSV import is read in the browser to add records; the selected file itself is not uploaded or stored by the import feature. CSV exports are generated when a user requests a download. The resulting downloaded file is controlled by the user and their device.' },
    { title: 'Retention, access, and deletion', body: 'Workspace information remains available while the account and business workspace are active. Users can edit or remove supported records in the app and can request account deletion from Settings. Deleting an account removes that user and, when they are the sole member, the associated business workspace and its records. Shared workspaces must be transferred before the owner can delete their account; the shared business is retained for its other members. Some records may need to be retained where required by law or for payment, security, or dispute records. Exact backup-retention periods depend on the service providers and are not stated here.' },
    { title: 'Security and international processing', body: 'BizPilot uses sign-in controls and business-level access rules to help protect workspace records. No online service can promise absolute security. BizPilot and its providers may process information in countries different from where the user or customer is located. The operator must confirm applicable transfer safeguards and local privacy obligations before launch.' },
    { title: 'Privacy requests and contact', body: `Users can manage their account and records in BizPilot and can request account deletion in Settings. Contact ${serviceOperator} about privacy requests at ${contactEmail}, or by mail at ${operatorAddress}.` },
  ],
  terms: [
    { title: 'About these terms', body: `These terms describe use of BizPilot, a business-management service for products and inventory, customers, appointments and booking pages, invoices, payment records and payment links, expenses, reports, and related tools. Service operator: ${serviceOperator}; mailing address: ${operatorAddress}; contact: ${contactEmail}. These terms are governed by the laws of ${governingLaw}, subject to mandatory rights and protections that apply where a user lives.` },
    { title: 'Accounts and workspaces', body: 'Provide accurate account and business information, keep sign-in credentials secure, and use only workspaces you are authorized to access. You are responsible for activity performed through your account and for managing access granted to team members.' },
    { title: 'Your business records and customers', body: 'You remain responsible for the records you enter, their accuracy, and keeping any independent records required for your business. You must have an appropriate legal basis and provide any notices or obtain any permissions required before adding customer information, publishing a booking page, or sending booking, invoice, or payment links.' },
    { title: 'Payments and subscriptions', body: 'BizPilot lets a business record payments it receives and, where available and configured, create payment links through a payment provider. Recording a payment manually does not transfer money. Payment processing, identity checks, settlement, refunds, disputes, and provider fees are governed by the relevant provider’s terms. BizPilot subscription plans, prices, renewal, cancellation, and any applicable taxes must be shown at checkout; paid features depend on the plan and account configuration.' },
    { title: 'Inventory, invoices, and reports', body: 'You are responsible for reviewing stock quantities, prices, taxes, invoice details, and reports before relying on them or sharing them with a customer. Currency display or exchange-rate estimates do not convert existing accounting records or guarantee a transaction exchange rate. BizPilot is not accounting, tax, legal, or financial advice.' },
    { title: 'AI and third-party services', body: 'AI replies are generated from the question, chat context, and aggregate business summary available to the assistant. Review them before acting and do not submit sensitive or confidential information. Parts of BizPilot rely on third-party services, which may have separate terms, availability, and privacy practices.' },
    { title: 'Acceptable use and service availability', body: 'Do not use BizPilot unlawfully, attempt to access another business’s records, interfere with the service, or submit information you are not authorized to use. Features may change, be unavailable, or be limited by a connected provider or subscription plan. BizPilot may be interrupted for maintenance, security, or circumstances outside its control.' },
    { title: 'Account closure and changes to these terms', body: 'You can request account deletion in Settings. If you own a shared workspace, transfer ownership before deleting your account. Business records may be removed with a sole-member workspace, while shared workspaces remain for their other members. The current version and update date of these terms will appear on this page.' },
    { title: 'Contact and governing law', body: `Contact ${serviceOperator} at ${contactEmail} or by mail at ${operatorAddress}. These terms are governed by the laws of ${governingLaw}, subject to mandatory local consumer protections. Any dispute is subject to courts with jurisdiction under applicable Indian law.` },
  ],
};

export function LegalPage({ page }: { page: LegalKind }) {
  const isPrivacy = page === 'privacy';
  return <main className="legal-page">
    <header className="legal-header"><a className="legal-brand" href="/" aria-label="BizPilot home"><span className="brand-mark">B</span><span><strong>BizPilot</strong><small>BUSINESS MANAGER</small></span></a><a className="legal-back" href="/"><ArrowLeft size={15}/> Back to BizPilot</a></header>
    <article className="legal-document">
      <div className="legal-kicker">BIZPILOT · {isPrivacy ? 'PRIVACY' : 'TERMS'}</div>
      <div className="legal-title-row"><div><h1>{isPrivacy ? 'Privacy policy' : 'Terms of use'}</h1><p>{isPrivacy ? 'What information BizPilot handles and why.' : 'Rules for using BizPilot and its business tools.'}</p></div><span className="legal-title-icon">{isPrivacy ? <ShieldCheck size={19}/> : <FileText size={19}/>}</span></div>
      <p className="legal-review-note"><strong>Current service information</strong><span>This page describes BizPilot’s present features and the operator contact details supplied for this service. Rules can vary by country; businesses using BizPilot remain responsible for their own customer notices and legal obligations.</span></p>
      <p className="legal-date">Updated October 10, 2026</p>
      <div className="legal-sections">{sections[page].map((section, index) => <section key={section.title}><span className="legal-section-number">{String(index + 1).padStart(2, '0')}</span><div><h2>{section.title}</h2><p>{section.body}</p></div></section>)}</div>
      <footer className="legal-footer"><span>BizPilot</span><nav aria-label="Legal pages"><a href="/privacy">Privacy</a><a href="/terms">Terms</a><a href="/">Sign in</a></nav></footer>
    </article>
  </main>;
}
