import { useState, type FormEvent } from 'react';
import { Check, Copy, Megaphone, Pencil, Plus, Trash2, X } from 'lucide-react';
import type { Campaign } from '../types';
import './marketing.css';
export function MarketingPage({ campaigns, onCreate, onUpdate, onDelete }: { campaigns: Campaign[]; onCreate: (input: { name: string; channel: string; message: string }) => Promise<void>; onUpdate: (id: string, input: { name: string; channel: string; message: string }) => Promise<void>; onDelete: (id: string) => Promise<void> }) {
  const [open, setOpen] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [copied, setCopied] = useState(''); const [editingCampaign, setEditingCampaign] = useState<Campaign | null>(null); const [deleteId, setDeleteId] = useState(''); const [deleteError, setDeleteError] = useState('');
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); setSaving(true); setError(''); try { const input = { name: String(data.get('name') ?? '').trim(), channel: String(data.get('channel') ?? 'WhatsApp'), message: String(data.get('message') ?? '').trim() }; if (editingCampaign) await onUpdate(editingCampaign.id, input); else await onCreate(input); setOpen(false); setEditingCampaign(null); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not save this draft.'); } finally { setSaving(false); } }
  async function removeDraft(id: string) { setDeleteError(''); try { await onDelete(id); setDeleteId(''); } catch (reason) { setDeleteError(reason instanceof Error ? reason.message : 'Could not delete this draft.'); } }
  async function copy(campaign: Campaign) { try { await navigator.clipboard.writeText(campaign.message); setCopied(campaign.id); window.setTimeout(() => setCopied(current => current === campaign.id ? '' : current), 2200); } catch { setError('Could not copy this message. Check your browser clipboard permission.'); } }
  return <><div className="page-heading section-heading"><div><div className="eyebrow">WORKSPACE <span>/</span> MARKETING</div><h1>Marketing drafts</h1><p>Write and save promotional messages to use with your customers.</p></div><button className="primary-button" onClick={() => { setError(''); setEditingCampaign(null); setOpen(true); }}><Plus size={17}/>New draft</button></div><div className="marketing-note"><Megaphone size={16}/><span>BizPilot saves and copies your messages. You choose how and when to send them.</span></div><section className="marketing-list">{campaigns.map(campaign => <article className="panel marketing-card" key={campaign.id}><div className="marketing-card-heading"><div><span className="campaign-channel">{campaign.channel} · DRAFT</span><h2>{campaign.name}</h2></div><div className="marketing-card-actions"><button className="secondary-button marketing-copy" onClick={() => { setEditingCampaign(campaign); setError(''); setOpen(true); }}><Pencil size={14}/> Edit</button><button className="secondary-button marketing-copy" onClick={() => void copy(campaign)}>{copied === campaign.id ? <Check size={14}/> : <Copy size={14}/>} {copied === campaign.id ? 'Copied' : 'Copy message'}</button><button className="secondary-button marketing-copy delete-draft-button" onClick={() => { setDeleteError(''); setDeleteId(campaign.id); }}><Trash2 size={14}/> Delete</button></div></div>{deleteId === campaign.id && <div className="campaign-delete-confirm"><span>Delete this draft?</span>{deleteError && <small role="alert">{deleteError}</small>}<button className="secondary-button" onClick={() => setDeleteId('')}>Keep draft</button><button className="delete-confirm-button" onClick={() => void removeDraft(campaign.id)}>Delete draft</button></div>}<p>{campaign.message}</p><small>Saved {new Date(campaign.createdAt).toLocaleDateString([], { month: 'short', day: 'numeric', year: 'numeric' })}</small></article>)}{campaigns.length === 0 && <section className="panel marketing-empty"><div><Megaphone size={20}/></div><strong>No drafts yet</strong><span>Create a message for a promotion or customer update.</span><button className="text-button" onClick={() => { setEditingCampaign(null); setOpen(true); }}>Create your first draft <Plus size={15}/></button></section>}</section>
    {open && <div className="modal-backdrop" onMouseDown={event => { if (event.target === event.currentTarget) { setOpen(false); setEditingCampaign(null); } }}><section className="customer-modal" role="dialog" aria-modal="true" aria-labelledby="campaign-title"><div className="modal-heading"><div><h2 id="campaign-title">{editingCampaign ? 'Edit marketing draft' : 'New marketing draft'}</h2><p>Save a message you can copy when you’re ready.</p></div><button className="icon-button" aria-label="Close form" onClick={() => { setOpen(false); setEditingCampaign(null); }}><X size={18}/></button></div><form onSubmit={submit}><label>Draft name<input name="name" required minLength={2} autoFocus defaultValue={editingCampaign?.name ?? ''} placeholder="e.g. October special"/></label><label>Channel<select name="channel" defaultValue={editingCampaign?.channel ?? 'WhatsApp'}><option>WhatsApp</option><option>Instagram</option><option>Email</option><option>Other</option></select></label><label>Message<textarea name="message" required minLength={2} maxLength={5000} rows={6} defaultValue={editingCampaign?.message ?? ''} placeholder="Write your promotion or customer update…"/></label>{error && <p className="form-error" role="alert">{error}</p>}<div className="modal-actions"><button type="button" className="secondary-button" onClick={() => { setOpen(false); setEditingCampaign(null); }}>Cancel</button><button type="submit" className="primary-button" disabled={saving}>{saving ? 'Saving…' : editingCampaign ? 'Save changes' : 'Save draft'}</button></div></form></section></div>}
  </>;
}
