import { formatCurrency, getBusinessCurrencyCode } from '../lib/currency';
import { useState, type FormEvent } from 'react';
import { Clock3, Pencil, Plus, Scissors, Trash2, X } from 'lucide-react';
import type { Service } from '../types';
import './services.css';

type ServiceInput = { name: string; description: string; durationMinutes: number; price: number };
export function ServicePage({ services, onCreate, onUpdate, onRemove }: { services: Service[]; onCreate: (input: ServiceInput) => Promise<void>; onUpdate: (id: string, input: ServiceInput) => Promise<void>; onRemove: (id: string) => Promise<void> }) {
  const [open, setOpen] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [editingService, setEditingService] = useState<Service | null>(null); const [confirmingId, setConfirmingId] = useState<string | null>(null); const [removingId, setRemovingId] = useState<string | null>(null);
  async function removeService(id: string) { setRemovingId(id); setError(''); try { await onRemove(id); setConfirmingId(null); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not remove this service.'); } finally { setRemovingId(null); } }
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const data = new FormData(event.currentTarget); setSaving(true); setError('');
    const input = { name: String(data.get('name') ?? '').trim(), description: String(data.get('description') ?? '').trim(), durationMinutes: Number(data.get('durationMinutes')), price: Number(data.get('price')) };
    try { if (editingService) await onUpdate(editingService.id, input); else await onCreate(input); setOpen(false); setEditingService(null); }
    catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not save this service.'); }
    finally { setSaving(false); }
  }
  return <><div className="page-heading section-heading"><div><div className="eyebrow">WORKSPACE <span>/</span> SERVICES</div><h1>Services</h1><p>Keep your services, appointment lengths, and prices in one place.</p></div><button className="primary-button" onClick={() => { setEditingService(null); setError(''); setOpen(true); }}><Plus size={17}/>Add service</button></div>
    {error && !open && <p className="form-error" role="alert">{error}</p>}
    <section className="panel service-grid">{services.map(service => <article className="service-card" key={service.id}><div className="service-icon"><Scissors size={18}/></div><div className="service-card-main"><strong>{service.name}</strong><span>{service.description || 'Business service'}</span></div><div className="service-card-actions"><div className="service-card-meta"><span><Clock3 size={13}/>{service.durationMinutes} min</span><strong>{formatCurrency(service.price)}</strong></div>{confirmingId === service.id ? <div className="service-confirm-actions"><span>Remove this service?</span><button className="service-confirm-remove" disabled={removingId === service.id} onClick={() => void removeService(service.id)}>{removingId === service.id ? 'Removing…' : 'Yes, remove'}</button><button className="service-edit-button" onClick={() => setConfirmingId(null)}>Keep</button></div> : <><button className="service-edit-button" aria-label={`Edit ${service.name}`} onClick={() => { setEditingService(service); setError(''); setOpen(true); }}><Pencil size={13}/>Edit</button><button className="service-delete-button" aria-label={`Remove ${service.name}`} onClick={() => { setError(''); setConfirmingId(service.id); }}><Trash2 size={13}/></button></>}</div></article>)}{services.length === 0 && <div className="service-empty"><div><Scissors size={20}/></div><strong>No services yet</strong><span>Add a service with its duration and price to get your catalog started.</span><button className="text-button" onClick={() => { setEditingService(null); setError(''); setOpen(true); }}>Add your first service <Plus size={15}/></button></div>}</section>
    {open && <div className="modal-backdrop" onMouseDown={event => { if (event.target === event.currentTarget) { setOpen(false); setEditingService(null); } }}><section className="customer-modal" role="dialog" aria-modal="true" aria-labelledby="service-title"><div className="modal-heading"><div><h2 id="service-title">{editingService ? 'Edit service' : 'Add a service'}</h2><p>{editingService ? 'Update this service in your catalog.' : 'Save a service you offer to customers.'}</p></div><button className="icon-button" aria-label="Close form" onClick={() => { setOpen(false); setEditingService(null); }}><X size={18}/></button></div><form onSubmit={submit}><label>Service name<input name="name" required minLength={2} autoFocus placeholder="e.g. Haircut and styling" defaultValue={editingService?.name}/></label><label>Description <span>(optional)</span><input name="description" placeholder="A short description" defaultValue={editingService?.description}/></label><div className="service-form-row"><label>Duration<input name="durationMinutes" type="number" min="5" max="480" step="5" defaultValue={editingService?.durationMinutes ?? 45} required/></label><label>Price ({getBusinessCurrencyCode()})<input name="price" type="number" min="0" step="0.01" placeholder="0.00" defaultValue={editingService?.price} required/></label></div>{error && <p className="form-error" role="alert">{error}</p>}<div className="modal-actions"><button type="button" className="secondary-button" onClick={() => { setOpen(false); setEditingService(null); }}>Cancel</button><button type="submit" className="primary-button" disabled={saving}>{saving ? 'Saving…' : editingService ? 'Save changes' : 'Save service'}</button></div></form></section></div>}</>;
}
