import { useEffect, useState, type FormEvent } from 'react';
import { Building2, UserRound } from 'lucide-react';
import { currencyName, supportedCurrencies, type CurrencyCode } from '../lib/currency';
import './settings.css';
export function SettingsPage({ businessName, fullName, currencyCode, onSave }: { businessName: string; fullName: string; currencyCode: CurrencyCode; onSave: (input: { businessName: string; fullName: string; currencyCode: CurrencyCode }) => Promise<void> }) {
  const [saving, setSaving] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  const [currencyDraft, setCurrencyDraft] = useState<CurrencyCode>(currencyCode);
  useEffect(() => setCurrencyDraft(currencyCode), [currencyCode]);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); setSaving(true); setMessage(''); setError(''); try { await onSave({ businessName: String(data.get('businessName') ?? '').trim(), fullName: String(data.get('fullName') ?? '').trim(), currencyCode: currencyDraft }); setMessage('Your profile was saved.'); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not save your profile.'); } finally { setSaving(false); } }
  return <><div className="page-heading section-heading"><div><div className="eyebrow">WORKSPACE <span>/</span> SETTINGS</div><h1>Settings</h1><p>Manage your business profile and owner details.</p></div></div><section className="panel settings-panel"><div className="settings-heading"><div className="settings-icon"><Building2 size={18}/></div><div><h2>Business profile</h2><p>These details appear in your BizPilot workspace.</p></div></div><form onSubmit={submit}><label>Business name<span className="settings-input-icon"><Building2 size={14}/></span><input name="businessName" required minLength={2} defaultValue={businessName}/></label><label>Owner name<span className="settings-input-icon"><UserRound size={14}/></span><input name="fullName" required minLength={2} defaultValue={fullName}/></label><label>Business currency<select value={currencyDraft} onChange={event => setCurrencyDraft(event.target.value as CurrencyCode)}>{supportedCurrencies.map(code => <option key={code} value={code}>{code} — {currencyName(code)}</option>)}</select></label><p className="settings-help">This is the currency your business records use. Changing it does not convert existing amounts, and currency is locked after you add prices or financial records. Customer-local currency display can be added separately.</p>{error && <p className="form-error" role="alert">{error}</p>}{message && <p className="settings-success" role="status">{message}</p>}<div className="modal-actions"><button className="primary-button" type="submit" disabled={saving}>{saving ? 'Saving…' : 'Save profile'}</button></div></form></section></>;
}
